apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-on-aws
  labels:
    app: kubernetes-on-aws
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-on-aws
  template:
    metadata:
      labels:
        app: kubernetes-on-aws
    spec:
      containers:
      - name: simple-node
        image: randalp/simple-node
        ports:
        - containerPort: 80
